# Generated by Django 4.2.4 on 2023-08-23 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(help_text='Entre com o nome', max_length=100)),
                ('idade', models.IntegerField(help_text='Entre com a idade')),
                ('salario', models.DecimalField(decimal_places=2, help_text='Entre com o salario', max_digits=8)),
                ('email', models.EmailField(help_text='Entre com o email', max_length=24)),
                ('telefone', models.CharField(max_length=20, verbose_name='Entre com o DDD e DDI')),
                ('dtNasc', models.DateField(help_text='Nascimento com o formato DD/MM/AAAA', verbose_name='Data de Nascimento')),
            ],
        ),
    ]
